---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: shapeshifter
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: stable

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    keys:
      - https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    repos:
      - https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
    optfix:
      - Bitwarden
      - sublime_text
      - sublime_merge
      # Do I need anything else here?
    install:
      - gnome-tweaks
      - solaar
      # solaar-udev # We're adding rules file directly
      - alacritty
      - sublime-text
      - sublime-merge
      - https://bitwarden.com/download/?app=desktop&platform=linux&variant=rpm
    remove:
      - input-remapper # Conflicts with Solaar

  - type: script 
    snippets:
      # Additional Bitwarden stuff to do
      - "ln -sf /usr/lib/opt/Bitwarden/bitwarden /etc/alternatives/bitwarden"
      # - "chcon system_u:object_r:usr_t:s0 /usr/share/polkit-1/actions/com.bitwarden.Bitwarden.policy"

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - com.discordapp.Discord
        - com.valvesoftware.Steam
        - org.libreoffice.LibreOffice
        - it.mijorus.gearlever
        - eu.betterbird.Betterbird
        - md.obsidian.Obsidian
        - org.kde.dolphin
        # - com.wps.Office
      remove:
        - page.tesk.Refine
        - io.github.input_leap.input-leap
        - org.mozilla.Thunderbird
        - org.gnome.DejaDup
        # - Also remove Gnome-tweaks flatpak if present?
    user: {} # Also add Flathub user repo, but no user packages

  - type: gnome-extensions
    install:
      - 779  # Clipboard Indicator
      - 3843 # Just Perfection
      - 6162 # Solaar addon
      - 7180 # Syncthing toggle
      - 4798 # Thinkpad battery thresholds
      - 986  # Thinkpad thermals
      # - 5090 # Space bar
      # - 4736 # Smart Auto Move
    # uninstall:
      # - GSConnect

    # Further examples

    # - type: systemd
    #   system:
    #     enabled:
    #       - exampleservice

    # - type: chezmoi
    #   repository: "https://git.moonlightwell.ru/fullmoon/dotfiles" # my dotfiles repo
    #   # TODO: clean repo from secrets, make public
    #   all-users: false # make users have to enable chezmoi manually
    #   file-conflict-policy: replace # override changed files with those from the repo

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

