---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: aenocyon
description: Personal OS image. Intended for Thinkpad X1Y5.
alt-tags:
  - stable
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: stable

modules:
  - from-file: modules/init.yml
  - from-file: modules/gnome.yml
  # - from-file: modules/overrides.yml      # Currently not used
  - from-file: modules/custom-flatpak.yml
  - from-file: modules/custom-rpm.yml
  - from-file: modules/crossover.yml
  # - from-file: modules/chezmoi.yml
  - from-file: modules/bling.yml
  - type: signing









