---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: shapeshifter
description: This is my personal OS image.
alt-tags:
  - stable
  - stable-weekly
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: stable

# Executed in order
modules:
  - from-file: modules/init.yml
  - from-file: modules/gnome.yml
  - from-file: modules/overrides.yml
  - from-file: modules/common-flatpak.yml
  - from-file: modules/common-rpm.yml
  - from-file: modules/crossover.yml
  # - from-file: modules/chezmoi.yml









